text = "CimData"
print (text)
print (type(text))

# print (text[0])
# print (text[1])
# print (text[2])
# print (text[3])
# print (text[4])
# print (text[5])
# print (text[6])
# print (text[7])
print (text[-1])
print (text[-2])
print (text[-3])
print (text[-4])
print (text[-5])
print (text[-6])
print (text[-7])